# Generated by Django 3.2.9 on 2022-01-10 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=0)),
                ('correctly', models.CharField(default='не проверено', max_length=13)),
                ('begin_lesson', models.DateTimeField(auto_now_add=True)),
                ('date_answer', models.DateTimeField(blank=True, null=True)),
                ('date_check', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numtask', models.IntegerField(default=0, verbose_name='Номер')),
                ('variant', models.IntegerField(default=0, verbose_name='Вариант')),
                ('question', models.TextField(blank=True, verbose_name='Условие')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('img', models.ImageField(blank=True, null=True, upload_to='task', verbose_name='Чертеж')),
                ('numclass', models.IntegerField(blank=True, default=0, verbose_name='класс')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='math_app.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
                'ordering': ['theme_id', 'numtask', 'variant'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npp', models.IntegerField(default=0, verbose_name='N п/п')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='math_app.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=512)),
                ('partition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='math_app.partition')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='math_app.theme', verbose_name='Тема'),
        ),
    ]
